sudo: false
addons:
  apt:
    packages:
    - oracle-java8-installer
language: scala
jdk:
- oraclejdk8
script:
- admin/build.sh
before_install:
- openssl aes-256-cbc -K $encrypted_950849751342_key -iv $encrypted_950849751342_iv
  -in secrets.tar.enc -out secrets.tar -d
